trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Install Node.js
  - task: UseNode@2
    inputs:
      versionSpec: '16.x'
      checkLatest: true

  # Install dependencies
  - script: |
      npm install
    workingDirectory: frontend
    displayName: 'Install Dependencies'

  # Run Linting
  - script: |
      npm run lint
    workingDirectory: frontend
    displayName: 'Run Linting'

  # Run Unit Tests
  - script: |
      npm test
    workingDirectory: frontend
    displayName: 'Run Unit Tests'

  # Build Angular App
  - script: |
      npm run build --prod
    workingDirectory: frontend
    displayName: 'Build Angular App'

  # Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'frontend/dist'
      artifactName: 'frontend-dist'
      publishLocation: 'Container'
